package com.example.chatterserver.model;

public enum MessageType {
    LOGIN, REGISTER, CHAT, PRIVATE_CHAT, GROUP_CHAT, SYSTEM, ERROR, HEARTBEAT, LOGOUT, ONLINE_USERS,
    OFFLINE_USERS, HISTORY_MESSAGES, USER_LOGIN, USER_LOGOUT, FILE, GROUP_CREATE, GROUP_DELETE,
    GROUP_ADD, GROUP_REMOVE, GROUP_RESPONSE, GROUP_INFO, GROUP_BROADCAST
}