// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	UserID  int64 `db:"user_id" json:"user_id"`
	Role    int16 `db:"role" json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_name, creator_id)
VALUES ($1, $2)
RETURNING group_id, group_name, creator_id, created_at
`

type CreateGroupParams struct {
	GroupName string `db:"group_name" json:"group_name"`
	CreatorID int64  `db:"creator_id" json:"creator_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.GroupName, arg.CreatorID)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT g.group_id, g.group_name, g.creator_id, g.created_at,
       u.username, u.nickname, u.avatar_url
FROM groups g
JOIN users u ON u.user_id = g.creator_id
WHERE g.group_id = $1
`

type GetGroupByIDRow struct {
	GroupID   int64              `db:"group_id" json:"group_id"`
	GroupName string             `db:"group_name" json:"group_name"`
	CreatorID int64              `db:"creator_id" json:"creator_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Username  string             `db:"username" json:"username"`
	Nickname  string             `db:"nickname" json:"nickname"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetGroupByID(ctx context.Context, groupID int64) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, groupID)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.CreatorID,
		&i.CreatedAt,
		&i.Username,
		&i.Nickname,
		&i.AvatarUrl,
	)
	return i, err
}

const getGroupHistory = `-- name: GetGroupHistory :many
SELECT m.message_id, m.sender_id, m.content, m.message_type, m.created_at,
       u.username, u.nickname, u.avatar_url,
       f.file_id, f.file_name, f.stored_file_name, f.file_size, f.file_type
FROM messages m
JOIN users u ON u.user_id = m.sender_id
LEFT JOIN files f ON f.message_id = m.message_id
WHERE m.group_id = $1
  AND ($2::bigint = 0 OR m.message_id < $2)
ORDER BY m.message_id DESC
LIMIT $3
`

type GetGroupHistoryParams struct {
	GroupID  *int64 `db:"group_id" json:"group_id"`
	BeforeID int64  `db:"before_id" json:"before_id"`
	Limit    int32  `db:"limit" json:"limit"`
}

type GetGroupHistoryRow struct {
	MessageID      int64              `db:"message_id" json:"message_id"`
	SenderID       int64              `db:"sender_id" json:"sender_id"`
	Content        string             `db:"content" json:"content"`
	MessageType    int16              `db:"message_type" json:"message_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Username       string             `db:"username" json:"username"`
	Nickname       string             `db:"nickname" json:"nickname"`
	AvatarUrl      string             `db:"avatar_url" json:"avatar_url"`
	FileID         *int64             `db:"file_id" json:"file_id"`
	FileName       *string            `db:"file_name" json:"file_name"`
	StoredFileName *string            `db:"stored_file_name" json:"stored_file_name"`
	FileSize       *int64             `db:"file_size" json:"file_size"`
	FileType       *string            `db:"file_type" json:"file_type"`
}

func (q *Queries) GetGroupHistory(ctx context.Context, arg GetGroupHistoryParams) ([]GetGroupHistoryRow, error) {
	rows, err := q.db.Query(ctx, getGroupHistory, arg.GroupID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupHistoryRow
	for rows.Next() {
		var i GetGroupHistoryRow
		if err := rows.Scan(
			&i.MessageID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FileID,
			&i.FileName,
			&i.StoredFileName,
			&i.FileSize,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT u.user_id, u.username, u.nickname, u.avatar_url, gm.role, gm.joined_at
FROM group_members gm
JOIN users u ON u.user_id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type GetGroupMembersRow struct {
	UserID    int64              `db:"user_id" json:"user_id"`
	Username  string             `db:"username" json:"username"`
	Nickname  string             `db:"nickname" json:"nickname"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	Role      int16              `db:"role" json:"role"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID int64) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	UserID  int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int16, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.GroupID, arg.UserID)
	var role int16
	err := row.Scan(&role)
	return role, err
}

const getMemberUsernames = `-- name: GetMemberUsernames :many
SELECT u.username
FROM group_members gm
JOIN users u ON u.user_id = gm.user_id
WHERE gm.group_id = $1
`

func (q *Queries) GetMemberUsernames(ctx context.Context, groupID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemberUsernames, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.group_id, g.group_name, g.creator_id, g.created_at,
       u.username, u.nickname, u.avatar_url
FROM groups g
JOIN group_members gm ON gm.group_id = g.group_id
JOIN users u ON u.user_id = g.creator_id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type GetUserGroupsRow struct {
	GroupID   int64              `db:"group_id" json:"group_id"`
	GroupName string             `db:"group_name" json:"group_name"`
	CreatorID int64              `db:"creator_id" json:"creator_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Username  string             `db:"username" json:"username"`
	Nickname  string             `db:"nickname" json:"nickname"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetUserGroups(ctx context.Context, userID int64) ([]GetUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGroupsRow
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.CreatorID,
			&i.CreatedAt,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroupMessage = `-- name: InsertGroupMessage :one
INSERT INTO messages (sender_id, group_id, message_type, content)
VALUES ($1, $2, $3, $4)
RETURNING message_id, created_at
`

type InsertGroupMessageParams struct {
	SenderID    int64  `db:"sender_id" json:"sender_id"`
	GroupID     *int64 `db:"group_id" json:"group_id"`
	MessageType int16  `db:"message_type" json:"message_type"`
	Content     string `db:"content" json:"content"`
}

type InsertGroupMessageRow struct {
	MessageID int64              `db:"message_id" json:"message_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertGroupMessage(ctx context.Context, arg InsertGroupMessageParams) (InsertGroupMessageRow, error) {
	row := q.db.QueryRow(ctx, insertGroupMessage,
		arg.SenderID,
		arg.GroupID,
		arg.MessageType,
		arg.Content,
	)
	var i InsertGroupMessageRow
	err := row.Scan(&i.MessageID, &i.CreatedAt)
	return i, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT COUNT(*) FROM group_members WHERE group_id = $1 AND user_id = $2
`

type IsGroupMemberParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	UserID  int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	UserID  int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
