// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFileByID = `-- name: GetFileByID :one
SELECT f.file_id, f.message_id, m.sender_id, m.receiver_id,
       f.file_name, f.stored_file_name, f.file_url, f.file_size, f.file_type,
       COALESCE(f.md5, '') AS md5, m.created_at
FROM files f
JOIN messages m ON m.message_id = f.message_id
WHERE f.file_id = $1
`

type GetFileByIDRow struct {
	FileID         int64              `db:"file_id" json:"file_id"`
	MessageID      int64              `db:"message_id" json:"message_id"`
	SenderID       int64              `db:"sender_id" json:"sender_id"`
	ReceiverID     *int64             `db:"receiver_id" json:"receiver_id"`
	FileName       string             `db:"file_name" json:"file_name"`
	StoredFileName string             `db:"stored_file_name" json:"stored_file_name"`
	FileUrl        string             `db:"file_url" json:"file_url"`
	FileSize       int64              `db:"file_size" json:"file_size"`
	FileType       *string            `db:"file_type" json:"file_type"`
	Md5            string             `db:"md5" json:"md5"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetFileByID(ctx context.Context, fileID int64) (GetFileByIDRow, error) {
	row := q.db.QueryRow(ctx, getFileByID, fileID)
	var i GetFileByIDRow
	err := row.Scan(
		&i.FileID,
		&i.MessageID,
		&i.SenderID,
		&i.ReceiverID,
		&i.FileName,
		&i.StoredFileName,
		&i.FileUrl,
		&i.FileSize,
		&i.FileType,
		&i.Md5,
		&i.CreatedAt,
	)
	return i, err
}

const getPrivateHistory = `-- name: GetPrivateHistory :many
SELECT m.message_id, m.sender_id, m.receiver_id, m.content, m.message_type, m.created_at,
       s.username AS sender_username, s.nickname AS sender_nickname,
       r.username AS receiver_username, r.nickname AS receiver_nickname,
       f.file_id, f.file_name, f.stored_file_name, f.file_size, f.file_type
FROM messages m
JOIN users s ON s.user_id = m.sender_id
JOIN users r ON r.user_id = m.receiver_id
LEFT JOIN files f ON f.message_id = m.message_id
WHERE m.receiver_id IS NOT NULL
  AND ((m.sender_id = $1 AND m.receiver_id = $2)
       OR (m.sender_id = $2 AND m.receiver_id = $1))
  AND ($3::bigint = 0 OR m.message_id < $3)
ORDER BY m.message_id DESC
LIMIT $4
`

type GetPrivateHistoryParams struct {
	UserId1  int64  `db:"user_id1" json:"user_id1"`
	UserId2  *int64 `db:"user_id2" json:"user_id2"`
	BeforeID int64  `db:"before_id" json:"before_id"`
	Limit    int32  `db:"limit" json:"limit"`
}

type GetPrivateHistoryRow struct {
	MessageID        int64              `db:"message_id" json:"message_id"`
	SenderID         int64              `db:"sender_id" json:"sender_id"`
	ReceiverID       *int64             `db:"receiver_id" json:"receiver_id"`
	Content          string             `db:"content" json:"content"`
	MessageType      int16              `db:"message_type" json:"message_type"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SenderUsername   string             `db:"sender_username" json:"sender_username"`
	SenderNickname   string             `db:"sender_nickname" json:"sender_nickname"`
	ReceiverUsername string             `db:"receiver_username" json:"receiver_username"`
	ReceiverNickname string             `db:"receiver_nickname" json:"receiver_nickname"`
	FileID           *int64             `db:"file_id" json:"file_id"`
	FileName         *string            `db:"file_name" json:"file_name"`
	StoredFileName   *string            `db:"stored_file_name" json:"stored_file_name"`
	FileSize         *int64             `db:"file_size" json:"file_size"`
	FileType         *string            `db:"file_type" json:"file_type"`
}

func (q *Queries) GetPrivateHistory(ctx context.Context, arg GetPrivateHistoryParams) ([]GetPrivateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPrivateHistory,
		arg.UserId1,
		arg.UserId2,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrivateHistoryRow
	for rows.Next() {
		var i GetPrivateHistoryRow
		if err := rows.Scan(
			&i.MessageID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
			&i.SenderUsername,
			&i.SenderNickname,
			&i.ReceiverUsername,
			&i.ReceiverNickname,
			&i.FileID,
			&i.FileName,
			&i.StoredFileName,
			&i.FileSize,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicHistory = `-- name: GetPublicHistory :many
SELECT m.message_id, m.sender_id, m.content, m.message_type, m.created_at,
       u.username, u.nickname,
       f.file_id, f.file_name, f.stored_file_name, f.file_size, f.file_type
FROM messages m
JOIN users u ON u.user_id = m.sender_id
LEFT JOIN files f ON f.message_id = m.message_id
WHERE m.receiver_id IS NULL AND m.group_id IS NULL
  AND ($1::bigint = 0 OR m.message_id < $1)
ORDER BY m.message_id DESC
LIMIT $2
`

type GetPublicHistoryParams struct {
	BeforeID int64 `db:"before_id" json:"before_id"`
	Limit    int32 `db:"limit" json:"limit"`
}

type GetPublicHistoryRow struct {
	MessageID      int64              `db:"message_id" json:"message_id"`
	SenderID       int64              `db:"sender_id" json:"sender_id"`
	Content        string             `db:"content" json:"content"`
	MessageType    int16              `db:"message_type" json:"message_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Username       string             `db:"username" json:"username"`
	Nickname       string             `db:"nickname" json:"nickname"`
	FileID         *int64             `db:"file_id" json:"file_id"`
	FileName       *string            `db:"file_name" json:"file_name"`
	StoredFileName *string            `db:"stored_file_name" json:"stored_file_name"`
	FileSize       *int64             `db:"file_size" json:"file_size"`
	FileType       *string            `db:"file_type" json:"file_type"`
}

func (q *Queries) GetPublicHistory(ctx context.Context, arg GetPublicHistoryParams) ([]GetPublicHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPublicHistory, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicHistoryRow
	for rows.Next() {
		var i GetPublicHistoryRow
		if err := rows.Scan(
			&i.MessageID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
			&i.Username,
			&i.Nickname,
			&i.FileID,
			&i.FileName,
			&i.StoredFileName,
			&i.FileSize,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (message_id, file_name, stored_file_name, file_url, file_size, file_type, md5)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING file_id
`

type InsertFileParams struct {
	MessageID      int64   `db:"message_id" json:"message_id"`
	FileName       string  `db:"file_name" json:"file_name"`
	StoredFileName string  `db:"stored_file_name" json:"stored_file_name"`
	FileUrl        string  `db:"file_url" json:"file_url"`
	FileSize       int64   `db:"file_size" json:"file_size"`
	FileType       *string `db:"file_type" json:"file_type"`
	Md5            *string `db:"md5" json:"md5"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.MessageID,
		arg.FileName,
		arg.StoredFileName,
		arg.FileUrl,
		arg.FileSize,
		arg.FileType,
		arg.Md5,
	)
	var file_id int64
	err := row.Scan(&file_id)
	return file_id, err
}

const insertPrivateMessage = `-- name: InsertPrivateMessage :one
INSERT INTO messages (sender_id, receiver_id, message_type, content)
VALUES ($1, $2, $3, $4)
RETURNING message_id, created_at
`

type InsertPrivateMessageParams struct {
	SenderID    int64  `db:"sender_id" json:"sender_id"`
	ReceiverID  *int64 `db:"receiver_id" json:"receiver_id"`
	MessageType int16  `db:"message_type" json:"message_type"`
	Content     string `db:"content" json:"content"`
}

type InsertPrivateMessageRow struct {
	MessageID int64              `db:"message_id" json:"message_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertPrivateMessage(ctx context.Context, arg InsertPrivateMessageParams) (InsertPrivateMessageRow, error) {
	row := q.db.QueryRow(ctx, insertPrivateMessage,
		arg.SenderID,
		arg.ReceiverID,
		arg.MessageType,
		arg.Content,
	)
	var i InsertPrivateMessageRow
	err := row.Scan(&i.MessageID, &i.CreatedAt)
	return i, err
}

const insertPublicMessage = `-- name: InsertPublicMessage :one
INSERT INTO messages (sender_id, message_type, content)
VALUES ($1, $2, $3)
RETURNING message_id, created_at
`

type InsertPublicMessageParams struct {
	SenderID    int64  `db:"sender_id" json:"sender_id"`
	MessageType int16  `db:"message_type" json:"message_type"`
	Content     string `db:"content" json:"content"`
}

type InsertPublicMessageRow struct {
	MessageID int64              `db:"message_id" json:"message_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertPublicMessage(ctx context.Context, arg InsertPublicMessageParams) (InsertPublicMessageRow, error) {
	row := q.db.QueryRow(ctx, insertPublicMessage, arg.SenderID, arg.MessageType, arg.Content)
	var i InsertPublicMessageRow
	err := row.Scan(&i.MessageID, &i.CreatedAt)
	return i, err
}
