// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	FileID         int64              `db:"file_id" json:"file_id"`
	MessageID      int64              `db:"message_id" json:"message_id"`
	FileName       string             `db:"file_name" json:"file_name"`
	StoredFileName string             `db:"stored_file_name" json:"stored_file_name"`
	FileUrl        string             `db:"file_url" json:"file_url"`
	FileSize       int64              `db:"file_size" json:"file_size"`
	FileType       *string            `db:"file_type" json:"file_type"`
	Md5            *string            `db:"md5" json:"md5"`
	UploadTime     pgtype.Timestamptz `db:"upload_time" json:"upload_time"`
}

type Group struct {
	GroupID   int64              `db:"group_id" json:"group_id"`
	GroupName string             `db:"group_name" json:"group_name"`
	CreatorID int64              `db:"creator_id" json:"creator_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GroupMember struct {
	GroupID  int64              `db:"group_id" json:"group_id"`
	UserID   int64              `db:"user_id" json:"user_id"`
	Role     int16              `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type Message struct {
	MessageID   int64              `db:"message_id" json:"message_id"`
	SenderID    int64              `db:"sender_id" json:"sender_id"`
	ReceiverID  *int64             `db:"receiver_id" json:"receiver_id"`
	GroupID     *int64             `db:"group_id" json:"group_id"`
	MessageType int16              `db:"message_type" json:"message_type"`
	Content     string             `db:"content" json:"content"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	UserID        int64              `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	Password      string             `db:"password" json:"password"`
	Nickname      string             `db:"nickname" json:"nickname"`
	AvatarUrl     string             `db:"avatar_url" json:"avatar_url"`
	Status        int16              `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	Bio           string             `db:"bio" json:"bio"`
	Email         *string            `db:"email" json:"email"`
	Gender        int16              `db:"gender" json:"gender"`
	BackgroundUrl string             `db:"background_url" json:"background_url"`
}
