// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, nickname)
VALUES ($1, $2, $3)
RETURNING user_id
`

type CreateUserParams struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
	Nickname string `db:"nickname" json:"nickname"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.Nickname)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const existsByUsername = `-- name: ExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, password, nickname, avatar_url, background_url, bio, email, gender, created_at
FROM users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID        int64              `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	Password      string             `db:"password" json:"password"`
	Nickname      string             `db:"nickname" json:"nickname"`
	AvatarUrl     string             `db:"avatar_url" json:"avatar_url"`
	BackgroundUrl string             `db:"background_url" json:"background_url"`
	Bio           string             `db:"bio" json:"bio"`
	Email         *string            `db:"email" json:"email"`
	Gender        int16              `db:"gender" json:"gender"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.AvatarUrl,
		&i.BackgroundUrl,
		&i.Bio,
		&i.Email,
		&i.Gender,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, password, nickname, avatar_url
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	UserID    int64  `db:"user_id" json:"user_id"`
	Username  string `db:"username" json:"username"`
	Password  string `db:"password" json:"password"`
	Nickname  string `db:"nickname" json:"nickname"`
	AvatarUrl string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, username, nickname, avatar_url, background_url, bio, email, gender, created_at
FROM users
WHERE username = $1
`

type GetUserProfileRow struct {
	UserID        int64              `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	Nickname      string             `db:"nickname" json:"nickname"`
	AvatarUrl     string             `db:"avatar_url" json:"avatar_url"`
	BackgroundUrl string             `db:"background_url" json:"background_url"`
	Bio           string             `db:"bio" json:"bio"`
	Email         *string            `db:"email" json:"email"`
	Gender        int16              `db:"gender" json:"gender"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, username string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, username)
	var i GetUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Nickname,
		&i.AvatarUrl,
		&i.BackgroundUrl,
		&i.Bio,
		&i.Email,
		&i.Gender,
		&i.CreatedAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE username = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, username)
	return err
}

const updateUserAvatarURL = `-- name: UpdateUserAvatarURL :exec
UPDATE users SET avatar_url = $2 WHERE user_id = $1
`

type UpdateUserAvatarURLParams struct {
	UserID    int64  `db:"user_id" json:"user_id"`
	AvatarUrl string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarURL, arg.UserID, arg.AvatarUrl)
	return err
}

const updateUserBackgroundURL = `-- name: UpdateUserBackgroundURL :exec
UPDATE users SET background_url = $2 WHERE user_id = $1
`

type UpdateUserBackgroundURLParams struct {
	UserID        int64  `db:"user_id" json:"user_id"`
	BackgroundUrl string `db:"background_url" json:"background_url"`
}

func (q *Queries) UpdateUserBackgroundURL(ctx context.Context, arg UpdateUserBackgroundURLParams) error {
	_, err := q.db.Exec(ctx, updateUserBackgroundURL, arg.UserID, arg.BackgroundUrl)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET nickname = COALESCE($2, nickname),
    bio = COALESCE($3, bio),
    email = COALESCE($4, email),
    gender = COALESCE($5, gender)
WHERE user_id = $1
`

type UpdateUserProfileParams struct {
	UserID   int64   `db:"user_id" json:"user_id"`
	Nickname string  `db:"nickname" json:"nickname"`
	Bio      string  `db:"bio" json:"bio"`
	Email    *string `db:"email" json:"email"`
	Gender   int16   `db:"gender" json:"gender"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.UserID,
		arg.Nickname,
		arg.Bio,
		arg.Email,
		arg.Gender,
	)
	return err
}
